markusschanta/awesome-jupyter

README.md
Note: I'm an employee of Sagemath, Inc., the company behind CoCalc.
Repo: https://github.com/DrXyzzy/awesome-jupyter
=> expand info line about CoCalc

README.md
Add PAWS - https://wikitech.wikimedia.org/wiki/PAWS
=> Add PAWS in Hosted Notebook Solutions

README.md
I don't know if it's better to place it in education or in community resources.
=> Add Jupyter Map

CONTRIBUTING.md
Change quotes from triple-backtick (reStructuredText) to single-backtick (MarkDown).
=> Fix markdown in CONTRIBUTING

README.md
[awesome-lint](https://github.com/sindresorhus/awesome-lint) pointed out a number of (mostly syntactical) issues with the list.
=> awesome-lint

README.md
https://github.com/ibleducation/jupyter-edx-grader-xblock
> Auto-grade a student assignment created as a Jupyter notebook, using the nbgrader Jupyter extension, and write the score in the Open edX gradebook
=> jupyter-edx-grader-xblock

README.md
=> Add GitHub topic links, search and PyPI classifier

README.md
add Developing Support section and jupyter-notify, it is a browser notification for Jupyter.
If you want to change the section name, plz change it
=> add Developing Support section and jupyter-notify

README.md
=> Fix spelling.

README.md
:wave: this is a very cool project!
https://github.com/esri/arcgis-python-api cc/ @rohitgeo
=> add ArcGIS Python API

README.md
rodeo is not available anymore, so deleted this item
=> delete rodeo item

README.md
Sorry I'm not really respecting the guideline here (One PR per project), but I've got a lot to add here
=> Add new widgets libraries

README.md
PR from https://github.com/ankostis/awesome-jupyter
=> Add Lantern into Jupyterlab extensions

README.md
Hi Markus, 
how’s it going? 
Deepnote has come a long way since we last spoke during winter and I think we’re ready to be featured as an Amazing Jupyter resource! Check this [link](https://beta.deepnote.com/invite?token=fhs8ur) for direct access. Curious to hear your thoughts!
PR from: https://github.com/Jirka-Lhotka/awesome-jupyter
=> Added a link to Deepnote

README.md
https://github.com/jeronimodeleon/awesome-jupyter
=> Added Spell.run to Hosted Notebook Solutions

README.md
Thanks for starting and maintaining this repo!
Here is a list of new JupyterLab extensions that are often useful to users, and hence worth adding to this list.
Adding all the entries at once since they are all JupyterLab extensions (and also to avoid 10+ PRs).
=> Add new JupyterLab extensions

README.md
Package that adds a copy button to DataFrame outputs.
=> Add pd-replicator

README.md
=> Add jupyterlab_templates

README.md
https://github.com/ploomber/ploomber
=> Request to include Ploomber

README.md
Hey @markusschanta 
just fixing a link.
Cheers!
=> Fixing Google Colab link

README.md
Hey @markusschanta 
the link times out for me (for a few times I've tried over the last days). I wouldn't include it as timeout isn't so awesome ;)
Cheers,
Peter
=> Removing dead link (times out)

README.md
Reference: https://github.com/jupyterhub/nbgitpuller
=> Add nbgitpuller to education section

README.md
JupyterHub extension for sharing dashboards with authentication - https://cdsdashboards.readthedocs.io/
Thank you for the Awesome Jupyter resource! A few users of my open source project have suggested I submit it to your repo - I hope it is useful to others too.
=> Add ContainDS Dashboards

README.md
In Rendering/Publishing/Conversion category.
=> jut: CLI to view notebook head/tail in terminal

README.md
=> Add Evidently

README.md
A Jupyter integration for versioning, managing, and sharing notebook checkpoints
=> Added Neptune

README.md
Hi, thanks for compiling this awesome list of resources! I would like to add [LineaPy](https://github.com/LineaLabs/lineapy), a new Jupyter extension that helps data science professionals transition from development to production more quickly.
=> Add LineaPy to extension list

README.md
=> Jupyter Project Documentation Link Added

README.md
repository: https://github.com/vizzuhq/ipyvizzu
=> Add ipyvizzu to visualization section

README.md
Hello - request review and approval on the inclusion of Explore Jupyter on your list.
It would be a good addition under COMMUNITY RESOURCES section of this article. Would you like to include it in your list? We'd love to hear your feedback.
Thanks!
=> Add Kandi link

README.md
Partly addresses https://github.com/markusschanta/awesome-jupyter/issues/131
=> Add jupyter-panel-proxy

README.md
Partly addresses https://github.com/markusschanta/awesome-jupyter/issues/131
=> Add PaneLite

README.md
=> Add Mineo.app

README.md
=> Naming section "Tables" in TOC (as in the body)

README.md
- Added pinggy.io to hosted notebook solutions
- Added a tutorial to share notebooks from localhost.
=> Add pinggy.io to hosted notebook solutions and add a tutorial to share notebooks from localhost.

README.md
Hey @markusschanta , may we add ITables to the table section?
The project is developed at https://github.com/mwouts/itables/ and the documentation is hosted at https://mwouts.github.io/itables/.
Thanks for maintaining this awesome list!
=> Add Interactive Tables

README.md
Hope it makes the cut! Thanks for being awesome.
=> Added jupyter-stack-trace

README.md
"JupyterQuiz is a tool for displaying interactive self-assessment quizzes in Jupyter notebooks and Jupyter Book."
In my experience it is a useful library for education and interactive assignments and notes.
=> Add JupyterQuiz (Education)
