markusschanta/awesome-jupyter

- README.md
Hello, Markus
I came across your nice awesome list for jupyter this week and I hoped that I could add [pyecharts](https://github.com/pyecharts/pyecharts), as I am one of the contributors. 
Pyecharts supports [28+ charts ranging from 2D, 3D and geo mapping](http://nbviewer.jupyter.org/github/pyecharts/pyecharts-users-cases/blob/master/notebook-users-cases/notebook-user-cases.ipynb). It supports data scientists using Jupyter, nteract and supports web developers with django and flask integration. It will be my and the team's pleasure that someone may find it useful.
Thanks
> Add pyecharts

- README.md
[ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet) is a library for building interactive visualisations with Leaflet.js maps in notebooks using the Jupyter widgets framework.
It is 
- a mature project (the first commit by Brian Granger dates back to 2015)
- actively maintained by Jupyter widget maintainers (primarily @SylvainCorlay) 
- has a strong user base (it has just shy of 50,000 downloads on [conda-forge](https://anaconda.org/conda-forge/ipyleaflet)).
> Add `ipyleaflet` to the visualisation section

- README.md
[jupyter-gmaps](https://github.com/pbugnion/gmaps) is a library for building interactive visualisations with Google maps in notebooks using the Jupyter widgets framework.
It is 
- a mature project (the first commit dates back to 2015)
- actively maintained by Jupyter widget maintainers (primarily myself) and members of the community (there are 13 existing contributors).
- has a strong user base (it has 27,000 downloads on [conda-forge](https://anaconda.org/conda-forge/ipyleaflet)) and 407 stars on GitHub.
> Add `jupyter-gmaps` to visualisation section

- README.md
[jupyterlab-go-to-definition](https://github.com/krassowski/jupyterlab-go-to-definition) extension allows to jump to the definition of a variable with your mouse (using <kbd>Alt</kbd> + <kbd>click</kbd>), or keyboard (with <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>B</kbd> shortcut):
The second version with support for both Python and R kernels was [warmly welcomed](https://twitter.com/krassowski_m/status/1080890436577906690) by the community.
> Add jupyterlab-go-to-definition extension

- README.md
1. New data science tool to publish & share jupyter notebooks as data blogs and web apps.
2. Jupyterlab extension for publishing to Kyso.
> Kyso Platform & Jupyterlab-Publish Extension

- README.md
Jupytext (https://github.com/mwouts/jupytext) implements a two-way conversion between Jupyter notebooks and various text formats. 
Jupytext is available as a command line tool, and as a plugin for either Jupyter Notebook or Jupyter Lab, cf. the [documentation](https://github.com/mwouts/jupytext/blob/master/README.md)
> Added Jupytext

- README.md
This pull request adds the jp_doodle package
https://github.com/AaronWatters/jp_doodle
which is used to build special purpose scientific visualizations.
> Add jp_doodle as a visualization package

- README.md
This change removes the `statusbar` entry, since this extension is now part of JupyterLab 1.0, and the links points to an archived repo.
> Remove statusbar extension (now in core JupyterLab)

- README.md
Extension to keep Python code automatically formatted using [black](https://github.com/psf/black).
> Add nb_black to extensions

- README.md
[jupyterlab-lsp](https://github.com/krassowski/jupyterlab-lsp) brings IDE superpowers (similar to, and using the same protocol VS Code) to JupyterLab.
Scope: jupyterlab-lsp includes code navigation (jump-to-definition), on-hover code tooltips, signature suggestions, linters (diagnostics), kernel-less autocompletion (including auto invocation on dot), and code-aware rename feature. More refactoring features are to be added.
Please feel free to shorten, or modify the description and/or title.
> Add language-server-protocol lab extension

- README.md
I have put it under `Rendering/Publishing/Conversion` category since ReviewNB is closest to nbdime from the list (which is listed under this category). 
Probably "Version Control" should be it's own category that should have nbdime, ReviewNB, jupyterlab_git etc. under it. Or at least the title should be modified to `Rendering/Publishing/Conversion/Version Control`. Let me know if you agree and I will make that change as part of this PR.
> Add version control category

- README.md
Added links for AI platform notebooks (which replaces Datalab) and also added a link for Google Cloud Dataproc + Jupyter
> Added links for new Google Cloud Jupyter services

- README.md
A new category, "Searching" would be helpful to list a couple of packages that provide search capabilities for local Jupyter notebooks.
One package, [nbscan](https://github.com/conery/nbscan), was previously listed under "Rendering/Publishing/Conversion". It does generalized searching of `.ipynb` files and is integrated with nbgrader. This PR moves nbscan under the new "Searching" heading.
Additionally, [Kapitsa](https://github.com/gitjeff05/kapitsa) -- developed by the author of this PR -- searches Jupyter notebooks for user supplied strings inside the _source_ and _metadata.tags_ fields. Kapitsa differs from nbascan in that it is more of a CLI and contains a few other functions for managing local notebooks.
I propose these packages be given their own section.
> Search category for Kapitsa and nbscan

- README.md
Python extension in VS Code supports notebooks
Source for VS Code is [here](https://github.com/microsoft/vscode)
Source for the Python Extension is [here](https://github.com/microsoft/vscode-python)
> Update to include VS Code

- README.md
Adds IllumiDesk to the education section. Open source repo [is located here](https://github.com/IllumiDesk/illumidesk).
> Update to include IllumiDesk

- README.md
[jupyter-manim](https://github.com/krassowski/jupyter-manim) is an extension which allows generation and display of [manim](https://github.com/3b1b/manim) videos straight from the notebook. The added value is in the interfacing and encoding/embedding.
Notes:
- not sure if it makes the cut for "awesome" list, but it seems to be enjoyed by the users. Also, I thought it would be nice to have all the visualisation extensions in one place.
- not sure if the convention of removing `jupyter-` prefix still stands (older entries do not have it), but as to distinguish the interface (jupyter-manim) from the tool itself (manim), I kept it.
> Propose manim visualisation engine integration

- README.md
GitHub Action for testing/scheduling Jupyter Notebooks
(It could also potentially go under Rendering/Publishing/Conversion as it is built on papermill which is listed there)
> Add treebeard to testing

- README.md
I added Jupylet to the Domain-Specific Projects section.
Jupylet is a library for creating 2d and 3d games, graphics, music and sound synthesizers interactively in a Jupyter notebook.
It was designed with three target audiences in mind:
- education: for kids learning to program.
- research: for creating controlling and rendering game environments for Deep Reinforcement Learning.
- sound: live music coding directly in a jupyter notebook.
And it has extensive documentation:
https://jupylet.readthedocs.io/en/latest/
> Add Jupylet

- README.md
Jupytext also belongs in the "Rendering/Publishing/Conversion" section. In fact, it may belong better there than in the "version control" section.
> Add Jupytext to Rendering/Publishing/Conversion also

- README.md
This PR adds the Elyra extension (https://github.com/elyra-ai/elyra), which (among other things) provides a visual pipeline editor for building and running notebook (or Python script) pipelines locally (aka in JupyterLab) or remotely (e.g. using Kubeflow Pipelines).
> Add Elyra extension

- README.md
Guild AI is an open source (Apache 2) project that supports machine
learning experiment and data science tracking. Guild supports running
Jupyter Notebooks as tracked experiments.
> Add Guild AI

- README.md
This PR adds [lux](https://github.com/lux-org/lux) to the awesome-jupyter list. Lux is a Python library and Jupyter widget that automatically recommends interesting visualizations to users when they are working with dataframes within Jupyter notebooks.
> Add lux to README

- README.md
Kepler.gl is a data-agnostic, high-performance web-based application for visual exploration of large-scale geolocation data sets. Built on top of Mapbox GL and deck.gl, kepler.gl can render millions of points representing thousands of trips and perform spatial aggregations on the fly. This documents its extension for Jupyter.
> Add Keplergl

- README.md
Ganimede is a tool to manage jupyter notebook as a direct coded interface. We can deploy a jupyter notebook, along with a project definition. We can test and update the jupyter in a sandbox environment. We can upgrade to next version of notebook by upgrading from an edited version. It solves the pain of versioning jupyter notebook and its changes as well as it makes it easy to directly integrate it to other systems of product as a microservice.
> Add Ganimede

- README.md
Hi there!
Jupyterlab-notifications is an extension that notifies users of notebook cell execution completions via browser notifications. There has been 8500+ pypi installs of this extension since March 2021 and is soon to be part of [conda-forge](https://github.com/conda-forge/staged-recipes/pull/16150). So I thought it would be good to share on this list!
> Add jupyterlab-notifications to the frontend/runtimes list

- README.md
Added Paperspace Gradient to the Hosted Notebook Solutions Section. Gradient is a Jupyter-backed data science IDE that allows users to easily spin up notebooks with high-powered GPUs attached for machine learning. It can also be used to kick off MLOps pipelines with access to workflows and model deployments.
> Add Paperspace to Hosted Notebook Solutions

- README.md
`databooks` is a package to ease the collaboration between data scientists that use Jupyter, by reducing the number of git conflicts between different notebooks and resolution of git conflicts when encountered.
The key features, as listed in the docs, include:
- CLI tool
- Clear notebook metadata
- Resolve git conflicts
- Simple to use
- Simple API for using modelling and comparing notebooks using [Pydantic](https://pydantic-docs.helpmanual.io/)
> Add databooks

- README.md
This PR adds [stickyland](https://github.com/xiaohk/stickyland) under the `JupyterLab extension` section.
StickyLand is an extension that enables JupyterLab users to create sticky cells. Users can easily create sticky cells and freely arrange them with simple drag-and-drop. Users can also automatically execute these cells. With multiple sticky cells, users can even create a fully-fledged interactive dashboard.
> Add stickyland

- README.md
There is a small typo in README.md.
Should read `functionality` rather than `functionaltiy`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, functionaltiy -> functionality

- README.md
repo: https://github.com/HFAiLab/jupyterlab_tensorboard_pro
This project is a more complete jupyterlab tensorboard project that has been newly maintained recently. I hope to promote it to others.
> Add jupyterlab_tensorboard_pro

- README.md
Hello, thanks for creating this awesome list! I would like to add [genv](https://github.com/run-ai/jupyterlab_genv), a new JupyterLab extension that helps data scientists to manage their GPU resources seamlessly and more efficiently.
> Add genv to extension list

- README.md
https://github.com/manzt/anywidget is a new Python library that greatly simplifies creating and publishing custom Jupyter Widgets. Unlike the traditional (cookiecutter) approach, with anywidget you 1) avoid fiddling with build steps and bundlers, 2) can prototype widgets from within a notebook, and 3) get a modern front-end developer experience. 
You can learn more in the introductory [blog post](https://anywidget.dev/blog/introducing-anywidget/).
> Add `anywidget`

- README.md
Linked to docs page instead of external site (https://qbraid.com or https://lab.qbraid.com) as suggested in `CONTRIBUTING.md`. The Docker image used to build qBraid Lab must remain private, but some of the individual custom extensions may be released as open-source in the coming months. Can update if/when that occurs. Let me know if there is anything else you need!
> Add qBraid to Hosted Nb Solutions

- README.md
Adding Jupyter-ai - Jupyter AI provides a user-friendly and powerful way to explore generative AI models in notebooks and improve your productivity in JupyterLab and the Jupyter Notebook.
> Add Jupyter-ai

- README.md
Hi, suggesting to add amphi-etl which is a Jupyterlab distribution providing a low-code ETL tool. Also available as a Jupyterlab extension.
https://github.com/amphi-ai/amphi-etl
> Add Amphi for Jupyterlab extension
